extends Node

signal language_changed(language: String)

const SETTINGS_PATH := "user://settings.cfg"

var current_language := "ru"

var translations := {
	"ru": {
		"lang.button": "RU / ENG",
		"lang.current": "Язык: RU",
		"common.close_hint": "Меню открыто. Нажми вариант или R, чтобы закрыть окно.",
		"common.not_enough_essence": "Недостаточно эссенции",
		"common.need_more_essence": "Нужно больше эссенции",
		"base.bank_essence": "Эссенция в банке: {value}",
		"base.chest_ready": "Сундук: {value} готово к сбору",
		"base.forge_online": "Кузня активна",
		"base.forge_offline": "Кузня не построена",
		"base.garden_grown": "Сад вырос",
		"base.garden_empty": "Сад пуст",
		"base.queued": "Подготовлено: {value}",
		"base.prompt.walk": "Гуляй по городу. Активны сундук, торговец, мастерская, дом и городские ворота.",
		"base.prompt.near": "Нажми E или левую кнопку мыши рядом с {value}.",
		"base.hint": "В городе спокойно. Подойди к городским воротам, когда будешь готов к забегу на пять волн.",
		"base.hotspot.chest": "сундуком",
		"base.hotspot.trader": "лавкой торговца",
		"base.hotspot.workshop": "доской мастерской",
		"base.hotspot.house": "дверью дома",
		"base.hotspot.gate": "городскими воротами",
		"base.world_label.chest": "Сундук",
		"base.world_label.trader": "Торговец",
		"base.world_label.workshop": "Мастерская",
		"base.world_label.house": "Дом",
		"base.world_label.gate": "Ворота",
		"base.menu.chest.title": "Сундук",
		"base.menu.chest.body_full": "[b]Возврат из города[/b]\nВ ящике ждёт {value} эссенции.",
		"base.menu.chest.collect": "Забрать {value} эссенции",
		"base.menu.chest.empty": "Сундук пуст. Пройди волны в городе, чтобы прислать сюда новую награду.",
		"base.menu.chest.empty_action": "Сейчас забирать нечего",
		"base.menu.trader.title": "Брокер Нерал",
		"base.menu.trader.body": "[b]Подготовка к вылазке[/b]\nПотрать накопленную эссенцию, чтобы усилить следующий забег.",
		"base.menu.trader.attack": "Заточка клинка (6)\n+1 к атаке на следующий забег",
		"base.menu.trader.hp": "Рацион (5)\n+1 к максимальному HP на следующий забег",
		"base.menu.trader.dash": "Сапоги тропы (5)\nБолее быстрый рывок и легче выйти из опасности",
		"base.menu.workshop.title": "Доска мастерской",
		"base.menu.workshop.body": "[b]Городская мастерская[/b]\nКузня: {forge}\nСад: {garden}\n\nКузня улучшает награду за вылазки. Сад добавляет небольшой бонус к каждому забегу.",
		"base.menu.workshop.built": "Построено",
		"base.menu.workshop.missing": "Не построено",
		"base.menu.workshop.build_forge": "Построить кузнечный маяк ({value})\nБольше награды и сильнее старт в вылазке",
		"base.menu.workshop.build_garden": "Посадить травяной сад ({value})\nДаёт небольшой бонус в будущих забегах",
		"base.menu.workshop.complete": "Мастерская завершена\nОба городских проекта уже активны",
		"base.menu.gate.title": "Городские ворота",
		"base.menu.gate.body": "[b]Городская вылазка[/b]\nПройди пять волн, забери награду района, а затем сигил вернёт тебя домой.\n{bonus_line}",
		"base.menu.gate.bonus_none": "Бонусы города пока не подготовлены.",
		"base.menu.gate.bonus_some": "Подготовленные бонусы: {value}",
		"base.menu.gate.depart": "Отправиться в город\nНачать вылазку на пять волн и переслать награду обратно в сундук",
		"base.menu.gate.map": "Открыть карту мира\nВыйти на процедурную карту и вернуться в столицу через поселение",
		"base.menu.gate.map_fresh": "За воротами лежит неизведанная дорога мира.",
		"base.menu.gate.map_resume": "Тропа на карте уже разведана. Можно продолжить путь с последней точки.",
		"base.menu.gate.stay": "Остаться в городе\nСначала ещё немного подготовиться",
		"base.banner.banked": "+{value} эссенции добавлено в банк",
		"base.banner.attack_packed": "Заточка клинка подготовлена",
		"base.banner.rations_packed": "Рационы упакованы",
		"base.banner.boots_ready": "Сапоги тропы настроены",
		"base.banner.forge_built": "Кузнечный маяк построен",
		"base.banner.garden_built": "Травяной сад посажен",
		"town.message.defeat": "Ты вернулся в город с пустыми руками, но ворота всё ещё открыты.",
		"town.message.victory": "Награда из города доставлена: {value} эссенции отправлено в сундук.",
		"run.title": "Shardfall Arena",
		"run.status.start": "Арена активна. Первая волна уже собирается...",
		"run.objective.start": "Переживи пять волн и сокруши Воеводу в финальном раунде.",
		"run.hint.start": "WASD — движение, ЛКМ — атака, Space — рывок. После первой комнаты появится второе оружие, переключение на 1 и 2.",
		"run.status.city_buffs": "Активные городские бонусы: {value}.",
		"run.wave.label_zero": "Волна 0 / {value}",
		"run.wave.label": "Волна {current} / {total}",
		"run.status.wave": "Волна {value}: удерживай центр и разрезай врагов.",
		"run.objective.remaining": "Осталось врагов: {value}",
		"run.banner.wave": "Волна {value}",
		"run.status.remaining": "В строю ещё {value} врагов.",
		"run.status.shot": "Выстрел ушёл точно. Держи дистанцию.",
		"run.status.victory": "Победа. Уничтожено {kills} врагов, собрано {essence} эссенции. Возврат в город через {time}...",
		"run.objective.victory": "Финальный счёт: {kills} убийств, пик комбо x{combo}",
		"run.hint.victory": "Сигил возврата активен. Награда уже ждёт тебя в сундуке на базе.",
		"run.status.wave_clear": "Волна {value} очищена. Передохни секунду...",
		"run.objective.upgrade_incoming": "Сейчас откроется выбор навыка...",
		"run.banner.wave_clear": "Волна {value} очищена",
		"run.status.air": "Ты рассёк воздух. Продолжай двигаться.",
		"run.status.hit": "Чистый удар. Попаданий: {value}.",
		"run.banner.execution": "Добивание +{value} эссенции",
		"run.health": "HP: {current} / {max}",
		"run.essence": "Эссенция: {value}",
		"run.combo.idle": "Комбо: нет",
		"run.combo.active": "Комбо: x{count}  {value}%",
		"run.banner.failed": "Забег провален",
		"run.status.defeat": "Ты пал в бою на волне {wave}. Возврат в город через {time}...",
		"run.objective.defeat": "Финальный счёт: {kills} убийств, {essence} эссенции.",
		"run.hint.defeat": "Отдохни, закупись и попробуй снова через городские ворота.",
		"run.menu.upgrade.title": "Выбери улучшение",
		"run.menu.upgrade.body": "Арена ставит бой на паузу между прорывами. Выбери одно улучшение, и следующая волна сразу загрузится.",
		"run.menu.upgrade.status": "Волна поставлена на паузу. Выбери улучшение.",
		"run.menu.upgrade.objective": "Кликни по одной из карточек улучшения.",
		"run.menu.upgrade.hint": "Цвет подсказывает тип бонуса: урон, темп, радиус, сустейн, живучесть или мобильность.",
		"run.menu.weapon.title": "Выбери оружие",
		"run.menu.weapon.body": "После первой комнаты можно взять оружие дальнего боя. Меч навсегда остаётся в первом слоте.",
		"run.menu.weapon.status": "Следующая комната ждёт. Возьми пистолет или продолжай только с клинком.",
		"run.menu.weapon.objective": "Выбери второе оружие на этот забег.",
		"run.menu.weapon.hint": "Клавиша 1 всегда возвращает к мечу. Клавиша 2 переключает на второй слот, если он занят.",
		"run.menu.weapon.pistol.name": "Взять пистолет",
		"run.menu.weapon.pistol.desc": "Быстрые выстрелы с безопасной дистанции. Удобно вскрывать стрелков и добирать быстрых врагов.",
		"run.menu.weapon.keep.name": "Остаться с мечом",
		"run.menu.weapon.keep.desc": "Простой и чистый путь. Никакого второго слота, только ближний бой.",
		"run.status.upgrade_applied": "Установлено улучшение {value}. Следующая волна собирается...",
		"run.status.weapon_selected": "Во второй слот экипирован {value}. Переключайся на 1 и 2.",
		"run.status.weapon_skipped": "Ты остался только с мечом. Следующая комната уже собирается.",
		"run.objective.prepare": "Приготовься к следующему прорыву.",
		"run.hint.weapon_ready": "ЛКМ атакует активным оружием. Нажимай 1 для меча и 2 для второго слота.",
		"run.weapon.label": "Оружие: {active}  |  1 {primary}  2 {secondary}",
		"weapon.sword": "Меч",
		"weapon.pistol": "Пистолет",
		"upgrade.edge.name": "Закалка лезвия",
		"upgrade.edge.desc": "+1 к базовому урону каждого удара.",
		"upgrade.haste.name": "Петля темпа",
		"upgrade.haste.desc": "Комбо собирается быстрее, а скорость движения немного растёт.",
		"upgrade.reach.name": "Длинная дуга",
		"upgrade.reach.desc": "Увеличивает радиус и ширину удара.",
		"upgrade.blood.name": "Кровяной контур",
		"upgrade.blood.desc": "Восстанавливает 1 HP за убийство ударом.",
		"upgrade.vigor.name": "Ядро мощи",
		"upgrade.vigor.desc": "+1 к максимальному HP и мгновенное лечение на 1.",
		"upgrade.blink.name": "Привод скачка",
		"upgrade.blink.desc": "Рывок становится длиннее, быстрее и чаще.",
		"bonus.attack": "+{value} к атаке",
		"bonus.hp": "+{value} к максимальному HP",
		"bonus.dash": "+{value} к рывку",
		"bonus.garden": "благословение сада",
		"bonus.forge": "кромка кузни",
		"house.title": "Кедровый дом",
		"house.prompt.default": "Походи по дому. Дверь ведёт обратно наружу.",
		"house.prompt.near": "Нажми E или левую кнопку мыши рядом с {value}.",
		"house.spot.bed": "кроватью",
		"house.spot.desk": "столом",
		"house.hint.default": "Это безопасная внутренняя комната. Вернись наружу, когда захочешь снова исследовать город.",
		"house.hint.garden": "Из сада тянет травами даже сюда. Следующая вылазка начнётся чуть сильнее.",
		"house.note.bed": "Тихий отдых. Город кажется безопаснее, когда есть куда возвращаться.",
		"house.note.desk": "На столе лежат карты района. Со временем здесь можно вырастить журнал квестов, чертежи и сюжетные заметки.",
		"house.label.bed": "Кровать",
		"house.label.desk": "Стол",
		"house.label.exit": "Выход",
		"world.title": "Карта мира",
		"world.status": "Текущая столица: {capital}. Открыто поселений: {count}.",
		"world.hint": "WASD для движения. Подойди к поселению и нажми E или ЛКМ, чтобы войти.",
		"world.near": "Рядом: {value}. Это точка входа в локацию.",
		"world.quest.pending": "Активные задания появятся при входе в новые точки.",
		"world.quest.empty": "Активных цепочек пока нет.",
		"world.quest.some": "Квесты: {value}",
		"world.minimap.title": "Миникарта",
		"world.minimap.hint": "Туман только на миникарте. Масштаб: {value}",
		"inventory.title": "Инвентарь и отряд",
		"inventory.close": "Закрыть",
		"inventory.section.shared": "Общий инвентарь",
		"inventory.section.roster": "Отряд",
		"inventory.help": "Кликни по предмету, затем по слоту, чтобы экипировать его. Клик по заполненному слоту без выбранного предмета снимает вещь обратно в обоз.",
		"inventory.resources": "Вес {current} / {capacity} | Валюта {currency} | Инструменты {tools} | Медицина {medicine} | Припасы {supplies}",
		"inventory.resources.missing": "Инвентарь отряда не найден.",
		"inventory.unit.none": "Боец не выбран.",
		"inventory.unit.unknown_class": "Неизвестный класс",
		"inventory.unit.summary": "{name}\nКласс: {class}\nВес: {weight} / {capacity}\nПостоянные раны: {wounds}",
		"inventory.unit.level": "{name} (ур. {level})",
		"inventory.slot.unavailable": "Недоступно",
		"inventory.slot.empty": "[Пусто]",
		"inventory.slot.head": "Голова",
		"inventory.slot.body": "Тело",
		"inventory.slot.main_hand": "Основная рука",
		"inventory.slot.off_hand": "Вторая рука",
		"inventory.slot.belt_1": "Пояс 1",
		"inventory.slot.belt_2": "Пояс 2",
		"inventory.slot.belt_3": "Пояс 3",
		"inventory.slot.belt_4": "Пояс 4",
		"inventory.status.selected": "Выбрано: {value}.",
		"inventory.status.cannot_place": "Этот предмет нельзя поместить в слот {value}.",
		"inventory.status.equip_failed": "Не удалось экипировать {value}.",
		"inventory.status.equipped": "Экипировано: {value}.",
		"inventory.status.moved_back": "{value} возвращён в общий инвентарь.",
		"inventory.item.empty": "Пусто",
		"inventory.item.durability": "прочн. {current}/{max}",
		"inventory.item.charges": "заряды {value}"
	},
	"en": {
		"lang.button": "RU / ENG",
		"lang.current": "Language: ENG",
		"common.close_hint": "Menu open. Click an option or press R to close it.",
		"common.not_enough_essence": "Not enough essence",
		"common.need_more_essence": "Need more essence",
		"base.bank_essence": "Bank Essence: {value}",
		"base.chest_ready": "Chest: {value} ready to collect",
		"base.forge_online": "Forge online",
		"base.forge_offline": "Forge offline",
		"base.garden_grown": "Garden grown",
		"base.garden_empty": "Garden empty",
		"base.queued": "Queued: {value}",
		"base.prompt.walk": "Walk through town. Chest, trader, workshop, house, and city gate are all active.",
		"base.prompt.near": "Press E or left click near {value}.",
		"base.hint": "The town is peaceful. Visit the city gate when you are ready for a five-wave run.",
		"base.hotspot.chest": "the stash chest",
		"base.hotspot.trader": "the trader stall",
		"base.hotspot.workshop": "the workshop board",
		"base.hotspot.house": "the house door",
		"base.hotspot.gate": "the city gate",
		"base.world_label.chest": "Chest",
		"base.world_label.trader": "Trader",
		"base.world_label.workshop": "Workshop",
		"base.world_label.house": "House",
		"base.world_label.gate": "City Gate",
		"base.menu.chest.title": "Stash Chest",
		"base.menu.chest.body_full": "[b]City returns[/b]\nThe crate hums with {value} essence waiting to be banked.",
		"base.menu.chest.collect": "Collect {value} essence",
		"base.menu.chest.empty": "The chest is empty. Clear the city waves to send new rewards home.",
		"base.menu.chest.empty_action": "Nothing to collect right now",
		"base.menu.trader.title": "Broker Neral",
		"base.menu.trader.body": "[b]Prepared supplies[/b]\nSpend stored essence to tune the next city run.",
		"base.menu.trader.attack": "Sharpening Oil (6)\n+1 attack for the next city run",
		"base.menu.trader.hp": "Ration Pack (5)\n+1 max HP for the next city run",
		"base.menu.trader.dash": "Trail Boots (5)\nFaster dash and better escape timing",
		"base.menu.workshop.title": "Workshop Board",
		"base.menu.workshop.body": "[b]Town workshop[/b]\nForge: {forge}\nGarden: {garden}\n\nThe forge improves expedition payouts. The garden adds a small blessing to each run.",
		"base.menu.workshop.built": "Built",
		"base.menu.workshop.missing": "Missing",
		"base.menu.workshop.build_forge": "Build Forge Beacon ({value})\nBigger expedition payout and a stronger start",
		"base.menu.workshop.build_garden": "Plant Herb Garden ({value})\nAdds a small blessing to future runs",
		"base.menu.workshop.complete": "Workshop complete\nBoth town projects are already active",
		"base.menu.gate.title": "City Gate",
		"base.menu.gate.body": "[b]City Expedition[/b]\nPush through five waves, secure the district reward, then the recall sigil pulls you back home.\n{bonus_line}",
		"base.menu.gate.bonus_none": "No queued town bonuses yet.",
		"base.menu.gate.bonus_some": "Queued town bonuses: {value}",
		"base.menu.gate.depart": "Depart for the city\nStart a five-wave run and send any reward back to the chest",
		"base.menu.gate.map": "Open world map\nTravel through the generated overworld and return via the capital",
		"base.menu.gate.map_fresh": "An unexplored world road waits beyond the gate.",
		"base.menu.gate.map_resume": "Your last trail is still there. You can continue from the previous point.",
		"base.menu.gate.stay": "Stay in town\nKeep preparing before you head out",
		"base.banner.banked": "+{value} essence banked",
		"base.banner.attack_packed": "Sharpening Oil packed",
		"base.banner.rations_packed": "Rations packed",
		"base.banner.boots_ready": "Trail boots tuned",
		"base.banner.forge_built": "Forge Beacon built",
		"base.banner.garden_built": "Herb Garden planted",
		"town.message.defeat": "You stagger back to town empty-handed, but the gate is still open.",
		"town.message.victory": "City reward secured: {value} essence sent to your chest.",
		"run.title": "Shardfall Arena",
		"run.status.start": "Arena online. First wave is forming...",
		"run.objective.start": "Survive five waves and break the Warlord in the final round.",
		"run.hint.start": "WASD move, LMB attack, Space dash. After the first room you can add a second weapon and swap with 1 and 2.",
		"run.status.city_buffs": "City buffs active: {value}.",
		"run.wave.label_zero": "Wave 0 / {value}",
		"run.wave.label": "Wave {current} / {total}",
		"run.status.wave": "Wave {value}: hold the center and cut them down.",
		"run.objective.remaining": "Enemies remaining: {value}",
		"run.banner.wave": "Wave {value}",
		"run.status.remaining": "{value} enemies still standing.",
		"run.status.shot": "Shots fired. Keep your spacing.",
		"run.status.victory": "Victory. {kills} foes destroyed, {essence} essence harvested. Recall to town in {time}...",
		"run.objective.victory": "Final score: {kills} kills, combo peak x{combo}",
		"run.hint.victory": "The recall sigil is active. Your reward is waiting in the base chest.",
		"run.status.wave_clear": "Wave {value} cleared. Catch your breath...",
		"run.objective.upgrade_incoming": "Skill draft incoming...",
		"run.banner.wave_clear": "Wave {value} Cleared",
		"run.status.air": "Your blade cut air. Keep moving.",
		"run.status.hit": "Clean slash. {value} hits landed.",
		"run.banner.execution": "Execution +{value} essence",
		"run.health": "HP: {current} / {max}",
		"run.essence": "Essence: {value}",
		"run.combo.idle": "Combo: idle",
		"run.combo.active": "Combo: x{count}  {value}%",
		"run.banner.failed": "Run Failed",
		"run.status.defeat": "You fell in battle on wave {wave}. Returning to town in {time}...",
		"run.objective.defeat": "Final score: {kills} kills, {essence} essence.",
		"run.hint.defeat": "Rest, trade, and try again from the city gate.",
		"run.menu.upgrade.title": "Choose Upgrade",
		"run.menu.upgrade.body": "The arena pauses between breaches. Pick one upgrade, then the next wave loads in.",
		"run.menu.upgrade.status": "Wave paused. Pick an upgrade to continue.",
		"run.menu.upgrade.objective": "Click one of the upgrade cards.",
		"run.menu.upgrade.hint": "Each color hints at the bonus type: damage, tempo, range, sustain, vitality, or mobility.",
		"run.menu.weapon.title": "Choose Weapon",
		"run.menu.weapon.body": "After the first room you can add a ranged weapon. The sword always stays in slot 1.",
		"run.menu.weapon.status": "The next room waits. Pick a sidearm or keep the blade.",
		"run.menu.weapon.objective": "Choose your second slot for this run.",
		"run.menu.weapon.hint": "Press 1 to return to the sword. Press 2 to swap to the second slot once you take a weapon.",
		"run.menu.weapon.pistol.name": "Take Pistol",
		"run.menu.weapon.pistol.desc": "Fast shots from a safe distance. Great for thinning ranged enemies before they close in.",
		"run.menu.weapon.keep.name": "Stay Blade-Only",
		"run.menu.weapon.keep.desc": "Keep the run simple and rely only on the sword for now.",
		"run.status.upgrade_applied": "{value} installed. Next wave is assembling...",
		"run.status.weapon_selected": "{value} equipped in slot 2. Use 1 and 2 to switch.",
		"run.status.weapon_skipped": "You stayed with the sword alone. The next room is forming.",
		"run.objective.prepare": "Prepare for the next breach.",
		"run.hint.weapon_ready": "LMB attacks with the active weapon. Press 1 for sword and 2 for the sidearm.",
		"run.weapon.label": "Weapon: {active}  |  1 {primary}  2 {secondary}",
		"weapon.sword": "Sword",
		"weapon.pistol": "Pistol",
		"upgrade.edge.name": "Edge Temper",
		"upgrade.edge.desc": "+1 base damage on every slash.",
		"upgrade.haste.name": "Tempo Loop",
		"upgrade.haste.desc": "Faster combo cadence and a little move speed.",
		"upgrade.reach.name": "Long Arc",
		"upgrade.reach.desc": "Increase slash range and width.",
		"upgrade.blood.name": "Blood Circuit",
		"upgrade.blood.desc": "Heal 1 HP whenever a slash secures a kill.",
		"upgrade.vigor.name": "Vigor Core",
		"upgrade.vigor.desc": "+1 max HP and heal 1 instantly.",
		"upgrade.blink.name": "Blink Drive",
		"upgrade.blink.desc": "Longer, faster dash with lower cooldown.",
		"bonus.attack": "+{value} attack",
		"bonus.hp": "+{value} max HP",
		"bonus.dash": "+{value} dash tune",
		"bonus.garden": "garden blessing",
		"bonus.forge": "forge edge",
		"house.title": "Cedar House",
		"house.prompt.default": "Walk around the house. The door leads back outside.",
		"house.prompt.near": "Press E or left click near {value}.",
		"house.spot.bed": "the bed",
		"house.spot.desk": "the desk",
		"house.hint.default": "This is a safe interior room. Step back outside when you want to continue exploring town.",
		"house.hint.garden": "The herb scent from the garden carries inside. Your next expedition starts a little stronger.",
		"house.note.bed": "A quiet rest. The town feels safer when there is something worth returning to.",
		"house.note.desk": "Hand-drawn district maps. One day this room can grow into quest logs, blueprints, and story notes.",
		"house.label.bed": "Bed",
		"house.label.desk": "Desk",
		"house.label.exit": "Exit",
		"world.title": "World Map",
		"world.status": "Current capital: {capital}. Settlements discovered: {count}.",
		"world.hint": "Use WASD to move. Approach a settlement and press E or left click to enter.",
		"world.near": "Nearby: {value}. This is an entry point into a location.",
		"world.quest.pending": "Active quests will appear after you enter new places.",
		"world.quest.empty": "No active quest chains yet.",
		"world.quest.some": "Quests: {value}",
		"world.minimap.title": "Mini Map",
		"world.minimap.hint": "Fog stays only on the mini map. Zoom: {value}",
		"inventory.title": "Inventory and Roster",
		"inventory.close": "Close",
		"inventory.section.shared": "Shared Inventory",
		"inventory.section.roster": "Roster",
		"inventory.help": "Click an item, then click a slot to equip it. Click a filled slot with no selected item to unequip.",
		"inventory.resources": "Weight {current} / {capacity} | Currency {currency} | Tools {tools} | Medicine {medicine} | Supplies {supplies}",
		"inventory.resources.missing": "No roster inventory found.",
		"inventory.unit.none": "No unit selected.",
		"inventory.unit.unknown_class": "Unknown",
		"inventory.unit.summary": "{name}\nClass: {class}\nCarry Weight: {weight} / {capacity}\nPermanent Wounds: {wounds}",
		"inventory.unit.level": "{name} (Lv.{level})",
		"inventory.slot.unavailable": "Not available",
		"inventory.slot.empty": "[Empty]",
		"inventory.slot.head": "Head",
		"inventory.slot.body": "Body",
		"inventory.slot.main_hand": "Main Hand",
		"inventory.slot.off_hand": "Off Hand",
		"inventory.slot.belt_1": "Belt 1",
		"inventory.slot.belt_2": "Belt 2",
		"inventory.slot.belt_3": "Belt 3",
		"inventory.slot.belt_4": "Belt 4",
		"inventory.status.selected": "Selected {value}.",
		"inventory.status.cannot_place": "That item cannot be placed into {value}.",
		"inventory.status.equip_failed": "Equip failed for {value}.",
		"inventory.status.equipped": "Equipped {value}.",
		"inventory.status.moved_back": "Moved {value} back to the shared inventory.",
		"inventory.item.empty": "Empty",
		"inventory.item.durability": "dur {current}/{max}",
		"inventory.item.charges": "charges {value}"
	}
}


func _ready() -> void:
	_load_language()


func t(key: String, params := {}) -> String:
	var table: Dictionary = translations.get(current_language, translations["ru"])
	var fallback: Dictionary = translations["en"]
	var template: String = str(table.get(key, fallback.get(key, key)))
	for param_key in params.keys():
		template = template.replace("{%s}" % str(param_key), str(params[param_key]))
	return template


func set_language(language: String) -> void:
	if not translations.has(language):
		return
	if current_language == language:
		return
	current_language = language
	_save_language()
	language_changed.emit(current_language)


func toggle_language() -> void:
	set_language("en" if current_language == "ru" else "ru")


func get_language() -> String:
	return current_language


func _load_language() -> void:
	var config := ConfigFile.new()
	if config.load(SETTINGS_PATH) == OK:
		var loaded: String = str(config.get_value("localization", "language", "ru"))
		if translations.has(loaded):
			current_language = loaded


func _save_language() -> void:
	var config := ConfigFile.new()
	config.set_value("localization", "language", current_language)
	config.save(SETTINGS_PATH)
